#pragma config(Sensor, port2,  frontDistance,  sensorVexIQ_Distance)
#pragma config(Sensor, port4,  touch,          sensorVexIQ_LED)
#pragma config(Sensor, port9,  rearBumper,     sensorVexIQ_Touch)
#pragma config(Sensor, port10, gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftWheel,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightWheel,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void SetMotorSpeedAndDirection(short speed)
{
	//Just for fun I added a touch sensor to display colors
	if (speed > 0)
	{
		setTouchLEDColor(touch, colorRedViolet);
	}
	else if (speed < 0)
	{
		setTouchLEDColor(touch, colorDarkOrange);
	}
	else
	{
		setTouchLEDColor(touch, colorBlueGreen);
	}

	setMotorSpeed(leftWheel, speed);
	setMotorSpeed(rightWheel, speed);
}

void SetMotorDistanceSpeedAndDirection(short rotations, short speed)
{
	//Resets the motor encoders to zero so the target calculatons starts from the beginning
	resetMotorEncoder(leftWheel);
	resetMotorEncoder(rightWheel);

	setMotorTarget(leftWheel, rotations, speed);
	setMotorTarget(rightWheel, rotations, speed);

	waitUntilMotorStop(leftWheel);
	waitUntilMotorStop(rightWheel);
}

void TurnLeft(int fastSpeed, int slowSpeed, int degrees)
{
	//Resert the gyro to zero
	resetGyro(gyro);

	while(getGyroDegrees(gyro) < degrees)
	{
		if(getDistanceValue(frontDistance) < 102)	//If distance is less than 4 inches
		{
			SetMotorDistanceSpeedAndDirection(-360, -25);	//2 full rotations backwards
		}

		setMotorSpeed(leftWheel, slowSpeed);
		setMotorSpeed(rightWheel, fastSpeed);
	}
}

void TurnRight(int fastSpeed, int slowSpeed, int degrees)
{
	//Resert the gyro to zero
	resetGyro(gyro);

	while(getGyroDegrees(gyro) > degrees)
	{
		if(getDistanceValue(frontDistance) < 102)	//If distance is less than 4 inches
		{
			SetMotorDistanceSpeedAndDirection(-360, -25);	//2 full rotations backwards
		}

		setMotorSpeed(leftWheel, fastSpeed);
		setMotorSpeed(rightWheel, slowSpeed);
	}
}

void Dance()
{
	setTouchLEDColor(touch, colorOrange);
	TurnLeft(75, 0, 30);
	setTouchLEDColor(touch, colorBlue);
	TurnRight(75, 0, -30);
	setTouchLEDColor(touch, colorRed);

	SetMotorDistanceSpeedAndDirection(180, 50);	//1/2 rotations forwards
	setTouchLEDColor(touch, colorGreen);
	SetMotorDistanceSpeedAndDirection(-180, -50);	//1/2 rotations backwards
	setTouchLEDColor(touch, colorYellow);

	TurnRight(75, 0, -30);
	setTouchLEDColor(touch, colorViolet);
	TurnLeft(75, 0, 30);
	setTouchLEDColor(touch, colorBlueGreen);

	SetMotorDistanceSpeedAndDirection(-180, -50);	//1/2 rotations backwards
	setTouchLEDColor(touch, colorLimeGreen);
	SetMotorDistanceSpeedAndDirection(180, 50);	//1/2 rotations forwards
	setTouchLEDColor(touch, colorDarkBlue);
}

task main()
{
	bool changedDirection = true;
	int legTime = 5*1000;

	srand(nClockMinutes); //Seeds the rand( generator

	clearTimer(t1);

	while(true)
	{
		if (nPgmTime < 60*1000)	//Only executes for 60 seconds or until the battery level gets below 30%
		{
			if(nImmediateBatteryLevel/1000 > 3)
			{
				if(getDistanceValue(frontDistance) < 203)	//If distance is less than 8 inches
				{
					if(getDistanceValue(frontDistance) < 102)	//If distance is less than 4 inches
					{
						SetMotorDistanceSpeedAndDirection(-360, -25);	//2 full rotations backwards

						if(getBumperValue(rearBumper) == 1)	//If the bumper switch is pressed while driving backwards
						{
							SetMotorSpeedAndDirection(0);	//Set power zero

							SetMotorDistanceSpeedAndDirection(360, 25);	//Roll forward one rotation
						}

						//Generates a random number. If the number is even (divisible by 2) turn left, else turn right
						if(rand() % 2 == 0)
						{
							TurnLeft(30, 5, 90);
						}
						else
						{
							TurnRight(30, 5, -90);
						}
					}
					else
					{
						SetMotorSpeedAndDirection(25);	//Set power to 25% and drive forwards
					}
				}
				else
				{
					if (time1[t1] < legTime)	//Drive for leg time
					{
						SetMotorSpeedAndDirection(50);	//Distance is greater than 6 inches. Full throttle forward
					}
					else
					{
						//After leg time elapses change direction
						//The pattern should be swipes across the floor
						SetMotorSpeedAndDirection(0);	//Set power zero

						if (changedDirection)
						{
							TurnRight(50, 1, -180);

							changedDirection = !changedDirection;
						}
						else
						{
							TurnLeft(50, 1, 180);

							changedDirection = !changedDirection;
						}

						clearTimer(t1);
					}
				}
			}
			else
			{
				playRepetitiveSound(soundGasFillup, 700);
				while(bSoundActive)
				{
					Dance();
				}

				break;
			}
		}
		else
		{
			playRepetitiveSound(soundTada, 700);
			while(bSoundActive)
			{
				Dance();
			}

			break;
		}
	}

	setTouchLEDColor(touch, colorNone);

	playRepetitiveSound(soundPowerOff2, 200);
}
